CREATE DATABASE "DebitControl"
GO 

USE  "DebitControl"

CREATE TABLE Debit(
	Id					INTEGER IDENTITY(1, 1) NOT NULL,
	Value				BIGINT NOT NULL,
	Description			VARCHAR(MAX) NOT NULL,
	Active				BIT NOT NULL,
	CreationDate		DATETIME NOT NULL,
	LastUpdateDate		DATETIME NULL,
	CONSTRAINT PK_Debit PRIMARY KEY(Id),
)
GO

 CREATE TABLE Payment(
	Id					INTEGER IDENTITY(1, 1) NOT NULL,
	Id_Debit			INTEGER NOT NULL,
	Value				BIGINT NOT NULL,
	Description			VARCHAR(MAX) NULL,
	CreationDate		DATETIME,
	CONSTRAINT PK_Payment PRIMARY KEY(Id),
	CONSTRAINT FK_Debit_Payment FOREIGN KEY (Id_Debit) REFERENCES Debit(Id),
)
GO

 CREATE TABLE PaymentHistory(
	Id					INTEGER IDENTITY(1, 1) NOT NULL,
	Id_Debit			INTEGER NOT NULL,
	Id_Payment          INTEGER NULL,
	RegisterDate		DATETIME NOT NULL,
	Observation			NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_DebitHistory PRIMARY KEY(Id),
	CONSTRAINT FK_Debit_DebitHistory FOREIGN KEY (Id_Debit) REFERENCES Debit(Id),
	CONSTRAINT FK_Payment_DebitHistory FOREIGN KEY (Id_Payment) REFERENCES Debit(Id),
 )
 GO